server:
  port: 8082
spring:
  ai:
    mcp:
      client:
        toolcallback:
          enabled: true
        name: x-mcp-client
#        sse:
#          connections:
#            server1:
#              url: http://127.0.0.1:8081/
#              sse-endpoint: sse?key=sk-e7030e17d1d64881a44a53b359af1644

    openai:
      base-url: https://api.deepseek.com
      chat:
        base-url: https://api.deepseek.com
        completions-path: /v1/chat/completions
        options:
          model: deepseek-chat
      api-key: sk-413c6606010c4852939181278ed7e4a2

mcp:
  sse:
    connections:
      mail:
        url: http://127.0.0.1:8081/
        sse-endpoint: sse?key=sk-e7030e17d1d64881a44a53b359af1644
      map:
        url: https://mcp.amap.com/
        sse-endpoint: sse?key=586393e6a16c30c652197348af1e78d1